services:
  # MongoDB service (only needed if not using MongoDB Atlas)
  # Comment this out if using MongoDB Atlas in production
  mongodb:
    image: public.ecr.aws/docker/library/mongo:7.0.14
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    # Uncomment the following if you need MongoDB only in development
    # profiles:
    #   - development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    # If you want logs with timestamps:
    # environment:
    #   - DEBUG=*

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data: